'priority:p0':
  - '(### Severity\nCritical)|(- \[x] Critical)'
'priority:p1':
  - '(### (Priority|Severity)\nHigh)|(- \[x] High)'
'priority:p2':
  - '(### (Priority|Severity)\nMedium)|(- \[x] Medium)'
'priority:p3':
  - '(### (Priority|Severity)\nLow)|(- \[x] Low)'
'pr:type:feat':
  - '(feat:|- \[x] Feature)'
'pr:type:fix':
  - '(fix:|- \[x] Bug fix)'
'type:bug':
  - '- \[x] Bug fix'
'type:enhancement':
  - '(- \[x] Feature|- \[x] Other)'
'affects:documentation':
  - '(- \[x] Documentation only|\bdoc[s]\b|\bdocumentation[s]\b)'
'affects:functionality':
  - '\bfunctionalit(?:y|ies)\b'
'affects:locale':
  - '(\blocale[s]?\b|\blocali(?:s|z)(?:e[d]?|ation)\b)'
'affects:permissions':
  - '\bpermission[s]?\b'
'status:proposed':
  - '.*'
'branch:stable':
  - '(\* \[x]  Stable)|(- \[x] Stable)'
'branch:next':
  - '(\* \[x]  Next)|(- \[x] Next)'
