name: Branch Merge [next -> next-replit]

on:
  push:
    branches: [next]
  schedule:
  # At 5 minutes past the hour
    - cron: '5 * * * *'
  # click the button on Github repo!
  workflow_dispatch:

jobs:
  branch_merge:
    runs-on: ubuntu-latest
    name: Merge source into target branch

    steps:
      - name: Merge branch 'next' into next-replit
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: Xayanide
          repo: Quaver
          source-branch: next
          target-branch: next-replit
          commit-message: "Merge branch 'next' into next-replit"
